name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USING: 'node20'
      PRE: 'setup.js'
      MAIN: 'index.js'
      POST: 'cleanup.js'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake
        id: snake-gif
        uses: Platane/snk@master
        with:
          github_user_name: mishmanners
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Show Build Status
        run: git status

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
